version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000"
    restart: always
    networks:
      - app-network
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    networks:
      - app-network
  redis:
    image: "redis:alpine"
    ports:
      - "6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
  nginx:
    build:
      context: ./nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    environment:
      - DEBUG=${DEBUG:-True} 
    volumes:
      - ./nginx/certs:/etc/nginx/certs

volumes:
  redis-data:

networks:
  app-network:

  